version: '3.7'
services:
  nobu-postgres:
    image: postgres:latest
    restart: always
    container_name: nobu-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  nobu-smtp-server:
    image: mailhog/mailhog:latest
    container_name: nobu-smtp-server
    restart: unless-stopped
    ports:
      - '2525:1025'
      - '2580:8025'


volumes:
  postgres: